### ISSUE TITLE
Error in Code Should SYNC1 be SYNC0

### ISSUE THREAD

**Issue by wogoos** [xxzl0130/CS5460#1]
https://github.com/xxzl0130/CS5460/blob/09c7c3842e26aedf82f562a517d3195b82ee3654/CS5460.cpp#L78

Dear reader, 
I hope I place this question at the right locations. I'm looking for a CS5460 library and found yours. I checked your CPP Code and that looks good to me except on one issue. At /CS5460.cpp#L78 you do a  instruction  data |= SPI.transfer(SYNC1);
If I read the CS5460 PDF spec well I see at page 10 fig 1 "SDO Read Timing" that sync1(0xFF) should be sync0 (0xFE). I haven't tried it yet and maybe it doesn't matter but is my understanding correct that Sync1 should be Sync0.
Please let me know because I'm planning to use your library and thanks for that. 
Regards Oscar Goos

**Comment by xxzl0130** [comment]
Thank you for your question.
After I compared different versions of the datasheet of CS5460, I found out that only a special version of CS5460 (CS5460A) notes that it must be SYNC0 instead of SYNC1 on the SDI port while reading data.
Meanwhile, all versions of the datasheet show that both SYNC0 and SYNC1 could be regard as NOP command, so I'm not sure if this version of code will run correctly on all CS5460 chips. In case that, I will commit a patch to change SYNC1 into SYNC0 at /CS5460.cpp#L78.
Thank you for your attention sincerely.

**Comment by wogoos** [comment]
Your welcome, I will check the two CS5460 and CS5460A because i didn't know that.
Regards Oscar

**Comment by wogoos** [comment]
If you can help me with one more thing, I checked the CS5460 and it only explains to me that the SYNC1/0  is used during initialization, it probably puts the state machine in command state after start up. It is interpreted in the state machine as a NOP and no more than 3 Consecutive SYNC1 should be written. I don't see any were why you write a SYNC0 ( i see that you already changed it) during a  CS5460::readRegister() Read operation. It probably doesn't matter neither. Am I missing something that you have seen and I don't.  I cant test it myself because I haven't have received the module yet. 
Hope you can explain this to me.
Regards Oscar

**Comment by xxzl0130** [comment]
I've tested the code last year and it worked correctly. So maybe it doesn't matter to use SYNC0 or SYNC1 while reading data.
Also I checked the data sheet and it shows that,

> During the read cycle, the SYNC0 command (NOP) should be strobed on the SDI port while clocking the data from the SDO port.

It means SYNC0 is regard as NOP, thus using SYNC1` as NOP is available probably.
But to be on the safe side, I've already changed SYNC1 into SYNC0.

PS. I wrote this code a year ago, and I didn't use it during this time, so I forget why I chose SYNC1 rather than SYNC0.
